### ISSUE TITLE
Request to elaborate the implementation of code in Azure functions

### ISSUE THREAD

**Issue by karishmaTCS** [koskila/KeyphraseExtraction#1]
Hello ,
This is a superp solution.
I would kindly request you to please elaborate on how to implement code in azure function.
I tried implementing ,but could not get the result.
Looking forward to a response from you.
Thanks.

**Comment by koskila** [comment]
Hi KarishmaTCS,

Thanks for the feedback! What kind of issues are you having in the implementation? You'll just need to deploy (or even copy-paste) this file's contents to an Azure function:
https://github.com/koskila/KeyphraseExtraction/blob/master/KeywordWebhookReceiver/HttpTriggerCSharp.cs

**Comment by koskila** [comment]
Let me know if you'd like more input on the matter, I'm closing this fnor now since I haven't heard any more from you :)
